@startuml
class Course {
  - courseName: String
  - instructors: Instructor[]
  - textbooks: Textbook[]

  + Course(courseName: String, instructors: Instructor[], textbooks: Textbook[])
  + getCourseName(): String
  + setCourseName(courseName: String): void
  + getInstructors(): Instructor[]
  + setInstructors(instructors: Instructor[]): void
  + getTextbooks(): Textbook[]
  + setTextbooks(textbooks: Textbook[]): void
  + toString(): String
}

class Instructor {
  - firstName: String
  - lastName: String
  - officeNumber: String

  + Instructor(firstName: String, lastName: String, officeNumber: String)
  + getFirstName(): String
  + setFirstName(firstName: String): void
  + getLastName(): String
  + setLastName(lastName: String): void
  + getOfficeNumber(): String
  + setOfficeNumber(officeNumber: String): void
  + toString(): String
}

class Textbook {
  - title: String
  - author: String
  - publisher: String

  + Textbook(title: String, author: String, publisher: String)
  + getTitle(): String
  + setTitle(title: String): void
  + getAuthor(): String
  + setAuthor(author: String): void
  + getPublisher(): String
  + setPublisher(publisher: String): void
  + toString(): String
}

Course o-- Instructor
Course o-- Textbook
@enduml
